### ISSUE TITLE
Configure Drinks on the Web Interface

### ISSUE THREAD

**Issue by Mavajax** [nebhead/PiTender#2]
Is ist possible to implement a way to configure the Drinks in the Web Interface ?

**Comment by nebhead** [comment]
Absolutely - This is definitely a feature I want to add in the future.  I'll work on this, but I have some other projects in the queue first so it might take a while.

**Comment by nebhead** [comment]
I'm happy to report that I have updated this project and created a Recipe Builder page to create new drinks and add ingredients to the database!!  I've also squashed a few other bugs and made some other big improvements (like bringing the whole project up to Python 3.x).  
![screenshot_recipe_drink](https://user-images.githubusercontent.com/19876886/102443209-076e7800-3fdb-11eb-851d-f59ce67cb0c5.png)

**Comment by Mavajax** [comment]
Wow thank you for the Update !
